### ISSUE TITLE
ошибки в переводе приложения в vk.com

### ISSUE THREAD

**Issue by EngelOk** [tvp/community#11]
1. вместо Do you want to help us? - Would you like to join us?
2. вместо For members - Member's login
3. убрать Do you already have an account? вместо него уже имеется Member's login
4. вместо Do you have questions or proposals? - Do you have a question or suggestion?
5. Contact us: предлагаю здесь не только e-mail вставить, но и другие доступны контакты, которые проверяются более менее регулярно.
6. когда нажимаешь Login - в новом окне вместо Login отображается - Войти. Нужно заменить на Login.
7. Просьба. Смена языка с русского на английский находится внизу, это очень неудобно. Есть ли возможность ее переместить сверху в строку, где находится Community Online Вход Регистрация. Желательно также, чтобы там был флажок - будет выделяться и наши англоговорящие друзья найдут, где поменять язык =)

**Comment by razbakov** [comment]
Исправлено

**Comment by EngelOk** [comment]
все проверила, все отлично! =)
