### ISSUE TITLE
Не правильная кодировка для полей в групах и постах

### ISSUE THREAD

**Issue by razbakov** [tvp/community#36]
Создать новую миграцию, где проапдейтить таблицы на кодировку utf8

**Comment by razbakov** [comment]
может быть нужно еще и отдельные столбцы обновить?

**Comment by bohdan-chechyn** [comment]
зачем?  я проверил - новые записи в утф8 уже добавляеются для всех столбцов, на проде насколько я понимаю это вручную было сделано
